version: '3.8'
services:
  techx_apigw:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    dns:
     - 8.8.8.8
     - 8.8.4.4       
     - 208.67.222.222
     - 208.67.220.220  
    env_file:
     - .env
    ports:
     - "5105:5105"       
